/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author vektorel
 */
public class TabloKayit extends javax.swing.JFrame {

    int sayac =-1;
    int secilensatir=0;
    /**
     * Creates new form TabloKayit
     */
    public TabloKayit() {
        initComponents();
        
        tblBasvuruTablosu.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblBasvuruTablosu.getColumnModel().getColumn(1).setPreferredWidth(70);
        tblBasvuruTablosu.getColumnModel().getColumn(2).setPreferredWidth(60);
        tblBasvuruTablosu.getColumnModel().getColumn(3).setPreferredWidth(80);
        tblBasvuruTablosu.getColumnModel().getColumn(4).setPreferredWidth(40);
        tblBasvuruTablosu.getColumnModel().getColumn(5).setPreferredWidth(150);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CinsiyetGrubu = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuduzenle = new javax.swing.JMenuItem();
        menusil = new javax.swing.JMenuItem();
        menugoster = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtadsoyad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttelefon = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        rbtnerkek = new javax.swing.JRadioButton();
        rbtnkadin = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cmbmeslek = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        spinneryas = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        chkingilizce = new javax.swing.JCheckBox();
        chkrusca = new javax.swing.JCheckBox();
        chkfransizca = new javax.swing.JCheckBox();
        chkcince = new javax.swing.JCheckBox();
        btnyenikayit = new javax.swing.JButton();
        btnkaydet = new javax.swing.JButton();
        btnduzenle = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBasvuruTablosu = new javax.swing.JTable();

        menuduzenle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Edit Property_48px.png"))); // NOI18N
        menuduzenle.setText("Düzenle");
        menuduzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuduzenleActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuduzenle);

        menusil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Delete_48px.png"))); // NOI18N
        menusil.setText("Sil");
        menusil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusilActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menusil);

        menugoster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Save Archive_48px.png"))); // NOI18N
        menugoster.setText("Kaydı Göster");
        jPopupMenu1.add(menugoster);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Ad Soyad");

        txtadsoyad.setEnabled(false);

        jLabel2.setText("Telefon");

        txttelefon.setEnabled(false);

        jLabel3.setText("Cinsiyet");

        CinsiyetGrubu.add(rbtnerkek);
        rbtnerkek.setText("Erkek");

        CinsiyetGrubu.add(rbtnkadin);
        rbtnkadin.setText("Kadın");

        jLabel4.setText("Meslek");

        cmbmeslek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doktor", "Mühendis", "Öğretmen", "Memur", "İşçi", "Polis", "Diğer" }));

        jLabel5.setText("Yaş");

        jLabel6.setText("Yabancı Dil");

        chkingilizce.setText("İngilizce");

        chkrusca.setText("Rusça");
        chkrusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkruscaActionPerformed(evt);
            }
        });

        chkfransizca.setText("Fransızca");

        chkcince.setText("Çince");

        btnyenikayit.setText("Yeni Kayıt");
        btnyenikayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyenikayitActionPerformed(evt);
            }
        });

        btnkaydet.setText("Kaydet");
        btnkaydet.setEnabled(false);
        btnkaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaydetActionPerformed(evt);
            }
        });

        btnduzenle.setText("Düzenle");
        btnduzenle.setEnabled(false);
        btnduzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnduzenleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtadsoyad))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbmeslek, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spinneryas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnyenikayit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnkaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnerkek, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnkadin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkfransizca)
                                    .addComponent(chkingilizce))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkrusca)
                                    .addComponent(chkcince))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addComponent(txttelefon)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnduzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtadsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbtnerkek)
                    .addComponent(rbtnkadin))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbmeslek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spinneryas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkingilizce)
                    .addComponent(chkrusca))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkfransizca)
                    .addComponent(chkcince))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnyenikayit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnduzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 481));

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblBasvuruTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ad Soyad", "Telefon", "Cinsiyet", "Meslek", "Yaş", "Yabancı Dil"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblBasvuruTablosu.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tblBasvuruTablosu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 480, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkruscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkruscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkruscaActionPerformed

    private void btnkaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaydetActionPerformed
     
        String adsoyad = txtadsoyad.getText();
        String telefon = txttelefon.getText();
        String cinsiyet= rbtnerkek.isSelected()==true ? "Erkek" : "Kadın";
        String meslek = cmbmeslek.getSelectedItem().toString();
        int yas = (int)spinneryas.getValue();
        String yabancidil="";
        yabancidil += chkingilizce.isSelected()==true ? "İngilizce, " : "";
        yabancidil += chkcince.isSelected()==true ? "Çince, " : "";
        yabancidil += chkfransizca.isSelected()==true ? "Fransızca, " : "";
        yabancidil += chkrusca.isSelected()==true ? "Rusça, " : "";
        
        tblBasvuruTablosu.setValueAt(adsoyad, sayac, 0);
        tblBasvuruTablosu.setValueAt(telefon, sayac, 1);
        tblBasvuruTablosu.setValueAt(cinsiyet, sayac, 2);
        tblBasvuruTablosu.setValueAt(meslek, sayac, 3);
        tblBasvuruTablosu.setValueAt(yas, sayac, 4);
        tblBasvuruTablosu.setValueAt(yabancidil, sayac, 5);
        btnkaydet.setEnabled(false);
        btnyenikayit.setEnabled(true);
        txtadsoyad.setEnabled(false);
        txttelefon.setEnabled(false);
        
      
    }//GEN-LAST:event_btnkaydetActionPerformed

    private void btnyenikayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyenikayitActionPerformed
       
          
        sayac++;
        btnkaydet.setEnabled(true);
        btnyenikayit.setEnabled(false);
        txtadsoyad.setText("");
        txttelefon.setText("");
        txtadsoyad.setEnabled(true);
        txttelefon.setEnabled(true);
        
        
    }//GEN-LAST:event_btnyenikayitActionPerformed

    private void menusilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusilActionPerformed
        int secilen = tblBasvuruTablosu.getSelectedRow();
        DefaultTableModel tbl = (DefaultTableModel)tblBasvuruTablosu.getModel();
        tbl.removeRow(secilen);
        
    }//GEN-LAST:event_menusilActionPerformed

    private void menuduzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuduzenleActionPerformed
        int secilen = tblBasvuruTablosu.getSelectedRow();
        secilensatir = secilen;
        String adsoyad = tblBasvuruTablosu.getValueAt(secilen,0).toString();
        String telefon = tblBasvuruTablosu.getValueAt(secilen,1).toString();
        String cinsiyet= tblBasvuruTablosu.getValueAt(secilen,2).toString();
        String meslek = tblBasvuruTablosu.getValueAt(secilen,3).toString();
        String yas =tblBasvuruTablosu.getValueAt(secilen,4).toString();
        String yabancidil=tblBasvuruTablosu.getValueAt(secilen,5).toString();
        txtadsoyad.setText(adsoyad);
        txttelefon.setText(telefon);
        if(cinsiyet.equals("Erkek"))
            rbtnerkek.setSelected(true);
                else
           rbtnkadin.setSelected(true);
        cmbmeslek.setSelectedItem(meslek);
        spinneryas.setValue(Integer.parseInt(yas));
        chkcince.setSelected(false);
        chkfransizca.setSelected(false);
        chkingilizce.setSelected(false);
        chkrusca.setSelected(false);
        
        
           String[] mydizi =   yabancidil.split(",");
               for (String string : mydizi) {
            if(chkcince.getText().equals(string.trim())) chkcince.setSelected(true);
            else if(chkfransizca.getText().equals(string.trim())) chkfransizca.setSelected(true);
            else if(chkingilizce.getText().equals(string.trim())) chkingilizce.setSelected(true);
            else if(chkrusca.getText().equals(string.trim())) chkrusca.setSelected(true);
                           
        }
               
           btnyenikayit.setEnabled(false);
           btnduzenle.setEnabled(true);
           txtadsoyad.setEnabled(true);
           txttelefon.setEnabled(true);
         
               
    }//GEN-LAST:event_menuduzenleActionPerformed

    private void btnduzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnduzenleActionPerformed
         btnyenikayit.setEnabled(true);
         btnduzenle.setEnabled(false);
         txtadsoyad.setEnabled(false);
         txttelefon.setEnabled(false);
            String adsoyad = txtadsoyad.getText();
        String telefon = txttelefon.getText();
        String cinsiyet= rbtnerkek.isSelected()==true ? "Erkek" : "Kadın";
        String meslek = cmbmeslek.getSelectedItem().toString();
        int yas = (int)spinneryas.getValue();
        String yabancidil="";
        yabancidil += chkingilizce.isSelected()==true ? "İngilizce, " : "";
        yabancidil += chkcince.isSelected()==true ? "Çince, " : "";
        yabancidil += chkfransizca.isSelected()==true ? "Fransızca, " : "";
        yabancidil += chkrusca.isSelected()==true ? "Rusça, " : "";
        
        tblBasvuruTablosu.setValueAt(adsoyad, secilensatir, 0);
        tblBasvuruTablosu.setValueAt(telefon, secilensatir, 1);
        tblBasvuruTablosu.setValueAt(cinsiyet, secilensatir, 2);
        tblBasvuruTablosu.setValueAt(meslek, secilensatir, 3);
        tblBasvuruTablosu.setValueAt(yas, secilensatir, 4);
        tblBasvuruTablosu.setValueAt(yabancidil, secilensatir, 5);
               
    }//GEN-LAST:event_btnduzenleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabloKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabloKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabloKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabloKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabloKayit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup CinsiyetGrubu;
    private javax.swing.JButton btnduzenle;
    private javax.swing.JButton btnkaydet;
    private javax.swing.JButton btnyenikayit;
    private javax.swing.JCheckBox chkcince;
    private javax.swing.JCheckBox chkfransizca;
    private javax.swing.JCheckBox chkingilizce;
    private javax.swing.JCheckBox chkrusca;
    private javax.swing.JComboBox<String> cmbmeslek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuduzenle;
    private javax.swing.JMenuItem menugoster;
    private javax.swing.JMenuItem menusil;
    private javax.swing.JRadioButton rbtnerkek;
    private javax.swing.JRadioButton rbtnkadin;
    private javax.swing.JSpinner spinneryas;
    private javax.swing.JTable tblBasvuruTablosu;
    private javax.swing.JTextField txtadsoyad;
    private javax.swing.JFormattedTextField txttelefon;
    // End of variables declaration//GEN-END:variables
}
